import type { ICustomSelectProps } from "./reusable/base-select";
import { getRoutePath } from "@/config/get-route-path";

export const date_list: ICustomSelectProps = {
  defaultValue: "jan",
  placeholder: "Select Date",
  items: [
    { value: "jan", label: "January" },
    { value: "feb", label: "February" },
    { value: "mar", label: "March" },
    { value: "apr", label: "April" },
    { value: "may", label: "May" },
    { value: "jun", label: "June" },
    { value: "jul", label: "July" },
    { value: "aug", label: "August" },
    { value: "sep", label: "September" },
    { value: "oct", label: "October" },
    { value: "nov", label: "November" },
    { value: "dec", label: "December" },
  ],
};

export const account_links: { link: string; icon: string; name: string }[] = [
  {
    link: getRoutePath("account"),
    icon: "/assets/harmburger/round-user.png",
    name: "Account",
  },
  {
    link: getRoutePath("my_tickets"),
    icon: "/assets/harmburger/ticket.png",
    name: "My Tickets",
  },
  {
    link: getRoutePath("listed_tickets"),
    icon: "/assets/harmburger/ticket.png",
    name: "Listed Tickets",
  },
];

export const africanCountries: { value: string; label: string }[] = [
  { value: "DZ", label: "Algeria" },
  { value: "AO", label: "Angola" },
  { value: "BJ", label: "Benin" },
  { value: "BW", label: "Botswana" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cabo Verde" },
  { value: "CM", label: "Cameroon" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo (Brazzaville)" },
  { value: "CD", label: "Congo (Kinshasa)" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "DJ", label: "Djibouti" },
  { value: "EG", label: "Egypt" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GH", label: "Ghana" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "KE", label: "Kenya" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "ML", label: "Mali" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "YT", label: "Mayotte" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "NA", label: "Namibia" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "RE", label: "Réunion" },
  { value: "RW", label: "Rwanda" },
  { value: "ST", label: "São Tomé and Príncipe" },
  { value: "SN", label: "Senegal" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "SS", label: "South Sudan" },
  { value: "SD", label: "Sudan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TG", label: "Togo" },
  { value: "TN", label: "Tunisia" },
  { value: "UG", label: "Uganda" },
  { value: "EH", label: "Western Sahara" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
];

export const africanCurrencies: ICustomSelectProps["items"] = [
  { value: "DZD", label: "Algerian Dinar" },
  { value: "AOA", label: "Angolan Kwanza" },
  { value: "XOF", label: "West African CFA Franc" },
  { value: "XAF", label: "Central African CFA Franc" },
  { value: "BWP", label: "Botswana Pula" },
  { value: "BIF", label: "Burundian Franc" },
  { value: "CVE", label: "Cape Verdean Escudo" },
  { value: "KMF", label: "Comorian Franc" },
  { value: "CDF", label: "Congolese Franc" },
  { value: "DJF", label: "Djiboutian Franc" },
  { value: "EGP", label: "Egyptian Pound" },
  { value: "ERN", label: "Eritrean Nakfa" },
  { value: "ETB", label: "Ethiopian Birr" },
  { value: "GMD", label: "Gambian Dalasi" },
  { value: "GHS", label: "Ghanaian Cedi" },
  { value: "GNF", label: "Guinean Franc" },
  { value: "KES", label: "Kenyan Shilling" },
  { value: "LSL", label: "Lesotho Loti" },
  { value: "LRD", label: "Liberian Dollar" },
  { value: "LYD", label: "Libyan Dinar" },
  { value: "MGA", label: "Malagasy Ariary" },
  { value: "MWK", label: "Malawian Kwacha" },
  { value: "MRU", label: "Mauritanian Ouguiya" },
  { value: "MUR", label: "Mauritian Rupee" },
  { value: "MAD", label: "Moroccan Dirham" },
  { value: "MZN", label: "Mozambican Metical" },
  { value: "NAD", label: "Namibian Dollar" },
  { value: "NGN", label: "Nigerian Naira" },
  { value: "RWF", label: "Rwandan Franc" },
  { value: "STN", label: "São Tomé and Príncipe Dobra" },
  { value: "SCR", label: "Seychellois Rupee" },
  { value: "SLL", label: "Sierra Leonean Leone" },
  { value: "SOS", label: "Somali Shilling" },
  { value: "ZAR", label: "South African Rand" },
  { value: "SSP", label: "South Sudanese Pound" },
  { value: "SDG", label: "Sudanese Pound" },
  { value: "SZL", label: "Swazi Lilangeni" },
  { value: "TZS", label: "Tanzanian Shilling" },
  { value: "TND", label: "Tunisian Dinar" },
  { value: "UGX", label: "Ugandan Shilling" },
  { value: "ZMW", label: "Zambian Kwacha" },
  { value: "ZWG", label: "Zimbabwe Gold" },
];

export const africanBanks: ICustomSelectProps["items"] = [
  { value: "standard_bank_group", label: "Standard Bank Group" },
  { value: "national_bank_of_egypt", label: "National Bank of Egypt" },
  { value: "banque_misr", label: "Banque Misr" },
  { value: "firstrand", label: "FirstRand" },
  { value: "absa_bank", label: "Absa Bank" },
  { value: "nedbank", label: "Nedbank" },
  { value: "attijariwafa_bank", label: "Attijariwafa Bank" },
  { value: "banque_populaire", label: "Banque Populaire" },
  { value: "bank_of_africa", label: "Bank of Africa" },
  { value: "access_bank", label: "Access Bank" },
  { value: "investec", label: "Investec" },
  { value: "banque_nationale_d_algerie", label: "Banque Nationale d'Algérie" },
  {
    value: "banque_exterieure_d_algerie",
    label: "Banque Extérieure d'Algérie",
  },
  { value: "ecobank", label: "Ecobank" },
  { value: "zenith_bank", label: "Zenith Bank" },
  {
    value: "commercial_international_bank",
    label: "Commercial International Bank",
  },
  { value: "united_bank_for_africa", label: "United Bank for Africa" },
  { value: "first_bank_of_nigeria", label: "First Bank of Nigeria" },
  {
    value: "commercial_bank_of_ethiopia",
    label: "Commercial Bank of Ethiopia",
  },
  { value: "qnb_al_ahli", label: "QNB Al Ahli" },
  { value: "banque_du_caire", label: "Banque du Caire" },
  {
    value: "arab_african_international_bank",
    label: "Arab African International Bank",
  },
  { value: "mauritius_commercial_bank", label: "Mauritius Commercial Bank" },
  { value: "guaranty_trust_bank", label: "Guaranty Trust Bank" },
  {
    value: "banque_de_l_agriculture_et_du_developpement_rural",
    label: "Banque de l'Agriculture et du Développement Rural",
  },
  { value: "kcb_group", label: "KCB Group" },
  { value: "societe_generale_morocco", label: "Société Générale Morocco" },
  { value: "equity_bank_group", label: "Equity Bank Group" },
  { value: "capitec_bank", label: "Capitec Bank" },
  {
    value: "credit_immobilier_et_hotelier",
    label: "Crédit Immobilier et Hôtelier",
  },
];
